local_planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    use_sim_time: True
    planner_id: "GridBased"
    path_distance: 4.0
    bezier_transition_threshold: 0.523
    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      

local_planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True